spring:
  application:
    name: module4
  datasource:
    url: jdbc:postgresql://localhost:5433/lms
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    liquibase:
      changelog: classpath:db/changelog/db.changelog-master.yaml
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect


  app:
    cleanup:
      cron: "0 0 3 * * *"