spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/lms
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  app:
    cleanup:
      cron: "0 0 3 1 1 *"